name: simple_online_store_api
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  redis: ^1.3.0
  json_annotation: ^3.1.0
  jaguar_jwt: ^2.1.6
  injectable: ^1.0.5
  get_it: ^5.0.1
  hasura_connect: ^2.0.0
  aqueduct: ^4.0.0-b1

dev_dependencies:
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  injectable_generator: ^1.0.6
  dotenv: ^2.0.0
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1

scripts:
  dev: pub run build_runner watch
  build: pub run build_runner build
